package com.example.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.entity.TblOrder;
import com.example.entity.TblOrderExample;

@Mapper
public interface TblOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    long countByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int deleteByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int insert(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int insertSelective(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    List<TblOrder> selectByExample(TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    TblOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblOrder record, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int updateByExample(@Param("record") TblOrder record, @Param("example") TblOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int updateByPrimaryKeySelective(TblOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    int updateByPrimaryKey(TblOrder record);
}