package com.example.entity;

import java.util.Date;

public class TblGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.goods_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.goods_nm
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String goodsNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.picture
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.price
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.stock
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Long stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.basic_info
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String basicInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.keyword
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.register_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.goods_id
     *
     * @return the value of tbl_goods.goods_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.goods_id
     *
     * @param goodsId the value for tbl_goods.goods_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.goods_nm
     *
     * @return the value of tbl_goods.goods_nm
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getGoodsNm() {
        return goodsNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.goods_nm
     *
     * @param goodsNm the value for tbl_goods.goods_nm
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setGoodsNm(String goodsNm) {
        this.goodsNm = goodsNm == null ? null : goodsNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.picture
     *
     * @return the value of tbl_goods.picture
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.picture
     *
     * @param picture the value for tbl_goods.picture
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.price
     *
     * @return the value of tbl_goods.price
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.price
     *
     * @param price the value for tbl_goods.price
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.stock
     *
     * @return the value of tbl_goods.stock
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.stock
     *
     * @param stock the value for tbl_goods.stock
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.basic_info
     *
     * @return the value of tbl_goods.basic_info
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getBasicInfo() {
        return basicInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.basic_info
     *
     * @param basicInfo the value for tbl_goods.basic_info
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setBasicInfo(String basicInfo) {
        this.basicInfo = basicInfo == null ? null : basicInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.keyword
     *
     * @return the value of tbl_goods.keyword
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.keyword
     *
     * @param keyword the value for tbl_goods.keyword
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.register_id
     *
     * @return the value of tbl_goods.register_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.register_id
     *
     * @param registerId the value for tbl_goods.register_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId == null ? null : registerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.del_flg
     *
     * @return the value of tbl_goods.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.del_flg
     *
     * @param delFlg the value for tbl_goods.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.regist_date
     *
     * @return the value of tbl_goods.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.regist_date
     *
     * @param registDate the value for tbl_goods.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods.update_date
     *
     * @return the value of tbl_goods.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods.update_date
     *
     * @param updateDate the value for tbl_goods.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}