package com.example.entity;

import java.util.Date;

public class TblOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.order_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.total_fee
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Long totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.buyer_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.name
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.furigana
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String furigana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.postal_code
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.address
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.delivery_time
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.delivery_status
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String deliveryStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.order_id
     *
     * @return the value of tbl_order.order_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.order_id
     *
     * @param orderId the value for tbl_order.order_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.total_fee
     *
     * @return the value of tbl_order.total_fee
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.total_fee
     *
     * @param totalFee the value for tbl_order.total_fee
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.buyer_id
     *
     * @return the value of tbl_order.buyer_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.buyer_id
     *
     * @param buyerId the value for tbl_order.buyer_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.name
     *
     * @return the value of tbl_order.name
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.name
     *
     * @param name the value for tbl_order.name
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.furigana
     *
     * @return the value of tbl_order.furigana
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getFurigana() {
        return furigana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.furigana
     *
     * @param furigana the value for tbl_order.furigana
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setFurigana(String furigana) {
        this.furigana = furigana == null ? null : furigana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.postal_code
     *
     * @return the value of tbl_order.postal_code
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.postal_code
     *
     * @param postalCode the value for tbl_order.postal_code
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.address
     *
     * @return the value of tbl_order.address
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.address
     *
     * @param address the value for tbl_order.address
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.delivery_time
     *
     * @return the value of tbl_order.delivery_time
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.delivery_time
     *
     * @param deliveryTime the value for tbl_order.delivery_time
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime == null ? null : deliveryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.delivery_status
     *
     * @return the value of tbl_order.delivery_status
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.delivery_status
     *
     * @param deliveryStatus the value for tbl_order.delivery_status
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus == null ? null : deliveryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.del_flg
     *
     * @return the value of tbl_order.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.del_flg
     *
     * @param delFlg the value for tbl_order.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.regist_date
     *
     * @return the value of tbl_order.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.regist_date
     *
     * @param registDate the value for tbl_order.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.update_date
     *
     * @return the value of tbl_order.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.update_date
     *
     * @param updateDate the value for tbl_order.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}