package com.example.entity;

import java.util.Date;

public class TblReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_review.review_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String reviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_review.goods_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_review.reviewer_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String reviewerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_review.comment
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_review.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private String delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_review.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_review.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_review.review_id
     *
     * @return the value of tbl_review.review_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_review.review_id
     *
     * @param reviewId the value for tbl_review.review_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setReviewId(String reviewId) {
        this.reviewId = reviewId == null ? null : reviewId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_review.goods_id
     *
     * @return the value of tbl_review.goods_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_review.goods_id
     *
     * @param goodsId the value for tbl_review.goods_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_review.reviewer_id
     *
     * @return the value of tbl_review.reviewer_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getReviewerId() {
        return reviewerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_review.reviewer_id
     *
     * @param reviewerId the value for tbl_review.reviewer_id
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setReviewerId(String reviewerId) {
        this.reviewerId = reviewerId == null ? null : reviewerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_review.comment
     *
     * @return the value of tbl_review.comment
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_review.comment
     *
     * @param comment the value for tbl_review.comment
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_review.del_flg
     *
     * @return the value of tbl_review.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_review.del_flg
     *
     * @param delFlg the value for tbl_review.del_flg
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg == null ? null : delFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_review.regist_date
     *
     * @return the value of tbl_review.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_review.regist_date
     *
     * @param registDate the value for tbl_review.regist_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_review.update_date
     *
     * @return the value of tbl_review.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_review.update_date
     *
     * @param updateDate the value for tbl_review.update_date
     *
     * @mbg.generated Sat Aug 05 15:00:28 JST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}